# Site settings
title: KanScript
email: 
description: > # this means to ignore newlines until "baseurl:"
  KanScript 是一个为 KanColleViewer 设计的 Lua 脚本执行环境。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://KanScript.ga" # the base hostname & protocol for your site
twitter_username: 
github_project: Shazi199/KanScript

# Build settings
markdown: kramdown
